name: Deploy Bookstore to AWS

on:
  workflow_dispatch:


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write

